### ISSUE TITLE
UnhandledPromiseRejectionWarning: fast_memoize_1.default is not a function

### ISSUE THREAD

**Issue by sahanpd** [micheleriva/krabs#9]
Hi, I just ran into the following issue after updating Krabs to the latest v0.013!  Even though the server is ready, it fails to load its tenants. I'm using an async config btw.

```
info  - server ready on port 3000
(node:18300) UnhandledPromiseRejectionWarning: TypeError: fast_memoize_1.default is not a function
    at D:\Git Repos\WireApps\webshop-next-app\node_modules\krabs\dist\index.js:60:71  
    at step (D:\Git Repos\WireApps\webshop-next-app\node_modules\krabs\dist\index.js:33:23)
    at Object.next (D:\Git Repos\WireApps\webshop-next-app\node_modules\krabs\dist\index.js:14:53)
    at D:\Git Repos\WireApps\webshop-next-app\node_modules\krabs\dist\index.js:8:71   
    at new Promise (<anonymous>)
    at __awaiter (D:\Git Repos\WireApps\webshop-next-app\node_modules\krabs\dist\index.js:4:12)
    at krabs (D:\Git Repos\WireApps\webshop-next-app\node_modules\krabs\dist\index.js:55:12)
    at D:\Git Repos\WireApps\webshop-next-app\server.js:16:31
    at Layer.handle [as handle_request] (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\layer.js:95:5)   
    at next (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\layer.js:95:5)   
    at D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\index.js:281:22
    at param (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\index.js:354:14)
    at param (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (D:\Git Repos\WireApps\webshop-next-app\node_modules\express\lib\router\index.js:410:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18300) UnhandledPromiseRejectionWarning: Unhandled 
promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` 
(see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 13)
(node:18300) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

krabs.config.js
```javascript
const tenant = require("./modules/tenant.module");

module.exports = async () => await tenant.getAllTenants();
```

package.json - scripts
```
"scripts": {
    "dev": "NODE_ENV=dev node server.js",
    "build": "next build",
    "nextstart": "next start",
    "start": "NODE_ENV=prod node server.js"
  },
```

**Comment by micheleriva** [comment]
@sahanpd I'm looking into that!

**Comment by sahanpd** [comment]
Got the notification for the update. Thanks! @micheleriva
